#!/usr/bin/env bash

LAMBDA=${BUILDKITE_PLUGIN_BUILDKITE_JENKINS_DEPLOY_GIT_LAMBDA}
JOB=${BUILDKITE_PLUGIN_BUILDKITE_JENKINS_DEPLOY_GIT_JOB}
IAM_ROLE=${BUILDKITE_PLUGIN_BUILDKITE_JENKINS_DEPLOY_GIT_IAM_ROLE}
REGION=eu-west-1

TAG=${JENKINS_PARAM_TAG:-BUILDKITE_COMMIT}

echo "Assume Role"
TEMP_ROLE=$(aws sts assume-role --role-arn="${IAM_ROLE}" --role-session-name=lambda-invoke)

export AWS_ACCESS_KEY_ID=$(echo ${TEMP_ROLE} | jq .Credentials.AccessKeyId | xargs)
export AWS_SECRET_ACCESS_KEY=$(echo ${TEMP_ROLE} | jq .Credentials.SecretAccessKey | xargs)
export AWS_SESSION_TOKEN=$(echo ${TEMP_ROLE} | jq .Credentials.SessionToken | xargs)

cat << EOF > input.txt
{"jenkins_job": "${JOB}", "tag": "${TAG}"}
EOF

aws lambda invoke \
    --invocation-type RequestResponse \
    --function-name=${LAMBDA} \
    --region=${REGION} \
    --payload=file://input.txt /tmp/outfile
