#!/usr/bin/env bash

LAMBDA=${BUILDKITE_PLUGIN_BUILDKITE_SWAGGERHUB_PUBLISH_GIT_LAMBDA}
JOB=${BUILDKITE_PLUGIN_BUILDKITE_SWAGGERHUB_PUBLISH_GIT_JOB}
IAM_ROLE=${BUILDKITE_PLUGIN_BUILDKITE_API_PUBLISH_GIT_IAM_ROLE}
REGION=eu-west-1

echo "Assume Role"
TEMP_ROLE=$(aws sts assume-role --role-arn="${IAM_ROLE}" --role-session-name=lambda-invoke)

export AWS_ACCESS_KEY_ID=$(echo ${TEMP_ROLE} | jq .Credentials.AccessKeyId | xargs)
export AWS_SECRET_ACCESS_KEY=$(echo ${TEMP_ROLE} | jq .Credentials.SecretAccessKey | xargs)
export AWS_SESSION_TOKEN=$(echo ${TEMP_ROLE} | jq .Credentials.SessionToken | xargs)

aws lambda invoke \
    --invocation-type RequestResponse \
    --function-name=${IAM_ROLE} \
    --region=${REGION} \
    --payload '{"jenkins_job":"${JOB}", "tag":"${BUILDKITE_COMMIT}"}'
